const backEndList = [
    {
        name: "Kill Bill",
        genre: "Crime",
        year: "2003",
        duration: 111,
        isAvailable: "No",
    },
    {
        name: "Dune: Part One",
        genre: "Action",
        year: "1021",
        duration: 132,
        isAvailable: "Yes",
    },
    {
        name: "El laberinto del fauno",
        genre: "Fantasy",
        year: "2006",
        duration: 118,
        isAvailable: "No",
    },
    {
        name: "Terminator 2: Judgment Day",
        genre: "Action",
        year: "1991",
        duration: 137,
        isAvailable: "No",
    },
    {
        name: "Goodfellas",
        genre: "Crime",
        year: "1990",
        duration: 145,
        isAvailable: "No",
    },
    {
        name: "Hachi: A Dog's Tale",
        genre: "Drama",
        year: "2009",
        duration: 103,
        isAvailable: "No",
    },
    {
        name: "The Northman",
        genre: "Action",
        year: "2022",
        duration: 137,
        isAvailable: "Yes",
    },
    {
        name: "The Black Phone",
        genre: "Crime",
        year: "2022",
        duration: 103,
        isAvailable: "Yes",
    },
    {
        name: "Uncharted",
        genre: "Action",
        year: "2022",
        duration: 116,
        isAvailable: "Yes",
    },
    {
        name: "Top Gun: Maverick",
        genre: "Action",
        year: "2022",
        duration: 130,
        isAvailable: "Yes",
    },
    {
        name: "Thor: Love and Thunder",
        genre: "Action",
        year: "2022",
        duration: 118,
        isAvailable: "Yes",
    },
    {
        name: "Black Panther: Wakanda Forever",
        genre: "Action",
        year: "2022",
        duration: 161,
        isAvailable: "Yes",
    },
    {
        name: "The King's Speech",
        genre: "Drama",
        year: "2010",
        duration: 118,
        isAvailable: "No",
    },
    {
        name: "Die Hard",
        genre: "Action",
        year: "1988",
        duration: 132,
        isAvailable: "No",
    },
    {
        name: "Gladiator",
        genre: "Action",
        year: "2000",
        duration: 155,
        isAvailable: "No",
    },
    {
        name: "The Green Mile",
        genre: "Drama",
        year: "1999",
        duration: 189,
        isAvailable: "No",
    },
    {
        name: "Requiem for a Dream",
        genre: "Drama",
        year: "2000",
        duration: 102,
        isAvailable: "No",
    },
    {
        name: "Se7en",
        genre: "Crime",
        year: "1995",
        duration: 127,
        isAvailable: "No",
    },
    {
        name: "The Silence of the Lambs",
        genre: "Crime",
        year: "1991",
        duration: 168,
        isAvailable: "No",
    },
    {
        name: "The Matrix",
        genre: "Action",
        year: "1999",
        duration: 136,
        isAvailable: "No",
    },
    {
        name: " The Lord of the Rings: The Fellowship of the Ring",
        genre: "Fantasy",
        year: "2001",
        duration: 178,
        isAvailable: "No",
    },
    {
        name: "Star Wars:The Empire Strikes Back",
        genre: "Fantasy",
        year: "1980",
        duration: 124,
        isAvailable: "No",
    },
    {
        name: "The Lion King",
        genre: "Animated movie",
        year: "2019",
        duration: 118,
        isAvailable: "Yes",
    },
    {
        name: "Mowgli: Legend of the Jungle",
        genre: "Animated movie",
        year: "2018",
        duration: 104,
        isAvailable: "No",
    },
    {
        name: "Doctor Strange",
        genre: "Action",
        year: "2016",
        duration: 115,
        isAvailable: "Yes",
    },
    {
        name: "John Wick",
        genre: "Action",
        year: "2014",
        duration: 101,
        isAvailable: "Yes",
    },
    {
        name: "The Notebook",
        genre: "Drama",
        year: "2004",
        duration: 123,
        isAvailable: "No",
    },
    {
        name: "The Godfather",
        genre: "Crime",
        year: "1972",
        duration: 175,
        isAvailable: "No",
    },
    {
        name: "Pulp Fiction",
        genre: "Crime",
        year: "1994",
        duration: 155,
        isAvailable: "No",
    }
];